### ISSUE TITLE
Getting 500 responses from histogram and mosaic endpoints instead of desired valid but empty response

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/plot.data#101]
Back end: dfalke-b
Study: India ICEMR Fever Surveillance
Subset on: Dengue, by Panbio Dengue Early ELISA = Positive

Histogram viz using main variable = Plasmodium falciparum asexual stages, by microscopy result

```
 500 Internal Server Error {"status":"server-error","message":"Unable to complete processing","requestId":"6BMaiK4IyotjWIvJ1cHszA"}
```
Works OK without the subsetting.

**Comment by d-callan** [comment]
ive put low cost, since its already mostly done in plot.data.

**Comment by d-callan** [comment]
i moved away from this in favor of things like mbio and line plot etc. but its been referenced a few times recently and seems like its probably increasing again in priority.

**Comment by danicahelb** [comment]
agree @d-callan this issue keeps cropping up so it is a priority to fix. thanks!

**Comment by d-callan** [comment]
qa should wait on this until @bobular is done as well

**Comment by d-callan** [comment]
hey @nkittur-uga just want to clarify for qa what the issue here was since its fairly specific. The breaking cases we saw across a variety of tickets all had to do w the particular combination of filters and variables chosen in the viz tab resulting in no remaining complete cases. to be explicitly clear, there WAS data remaining generally speaking after filtering alone. BUT the variables chosen in the viz tab either didnt have data for that subset or didnt have any data overlapping (collected at different time points etc)

**Comment by nkittur-uga** [comment]
I get an informative note: "The visualization cannot be made because there is no plottable data for currently selected variable(s) in the current subset." QA is complete.

**Comment by bobular** [comment]
Thanks @nkittur-uga :-)
