### ISSUE TITLE
Scatterplot response with one point is not an array

### ISSUE THREAD

**Issue by asizemore** [VEuPathDB/plot.data#135]
Noticed when working on the alpha div app with GEMS

<img width="1688" alt="Screen Shot 2022-03-04 at 12 28 28 PM" src="https://user-images.githubusercontent.com/11710234/156812594-7d0ccc94-445a-4fd9-bfe2-02c6da5348bd.png">

The x-axis variable here must only have one value. So the `seriesX` and `seriesY` are returning a single number, not an array with a single number.

**Comment by SheenaTomko** [comment]
@asizemore, this has been deployed. Should it be assigned to Dan for QA or one of the ClinEpi outreach team members?

**Comment by asizemore** [comment]
@SheenaTomko i should move this back to Ready for Deploy. plot.data is on a different deploy mechanism than the web-eda and web-components code, and while this PR has been merged, it hasn't been deployed yet. I'll move it to Ready For Testing when it's deployed!

**Comment by aaronwlsong** [comment]
Looks good now in scatter plot, closing ticket.

Tested several vars of GEMS1 case control on microbiome website with alpha diversity app- scatter plot.
<img width="1485" alt="Screen Shot 2022-04-15 at 9 50 27 AM" src="https://user-images.githubusercontent.com/61077845/163579879-ed13cde4-ea26-4940-90d8-6c4c1957642e.png">
<img width="1723" alt="Screen Shot 2022-04-15 at 9 52 29 AM" src="https://user-images.githubusercontent.com/61077845/163579880-f9d31f42-38b6-45b6-be9f-216d90a6b011.png">
<img width="1760" alt="Screen Shot 2022-04-15 at 9 52 54 AM" src="https://user-images.githubusercontent.com/61077845/163579882-8f3a328b-78fe-4e32-a0ea-3b00c657a934.png">
<img width="1576" alt="Screen Shot 2022-04-15 at 9 53 37 AM" src="https://user-images.githubusercontent.com/61077845/163579886-d2919d91-7cfa-4145-8917-8c0ebf68a920.png">

Fyi: this issue seems only be fixed for scatter plot. In alpha diversity app - box plot, the issue still exists. If it needs, should open another ticket for same issue in different plot.
