### ISSUE TITLE
500 from lineplot when a proportion value is unknowingly filtered out 

### ISSUE THREAD

**Issue by bobular** [VEuPathDB/plot.data#157]
GEMS1
Line plot
x-axis: Age group
y-axis: Case or Control  case/case+control
overlay: **Lost earnings due to care**

or Borrowing, or is seems any variable uner Current care expenses.

![image](https://user-images.githubusercontent.com/308639/163461289-6974dbc0-bc3b-450a-bbdf-575607c33817.png)

What does work?

As above but with (three scenarios listed below)

- y-axis: numeric variable, like Age.
- y-axis: Participant->Sex female/male+female
- overlay: Participant->Sex

It's not obvious to me what the pattern is!
I couldn't get a similar 500 in other visualizations using the **Lost earnings due to care** overlay

**Comment by asizemore** [comment]
Pushed to b58. Issue is that there is no overlay data for Control participants, which means the proportion is basically Case/Case. Our plan is to still err, but return a nice error to the user. Will require work from front and back end.

**Comment by danicahelb** [comment]
link to 4/15 convo in Slack #eda-map-client-imp
https://epvb.slack.com/archives/C012ZK4Q5CZ/p1650035476658289

**Comment by danicahelb** [comment]
discussed in 6/1 data viz meeting. we've decided that -- for proportions -- we will allow numerator=denominator and we’ll return all 1s.

**Comment by asizemore** [comment]
@danicahelb the issue in this ticket is that the 500 is being thrown not because the num and denom are the same but because there are no samples left with the value of Control. Effectively the lack of data makes it Case/Case, but the user did not choose that. It's a very rare situation. Still, feels like we should somehow alert the user that they subsetted away an entire portion of the denominator? Without an alert, the user would just see a line plot with 1s and nulls and not necessarily know why.

In general being able to select the same num and denominator (for example in the screenshot below) is a different issue. I think the below is more what we talked about at the data viz meeting last week and i can implement a fix if it's a must have for b58.

<img width="1753" alt="Screen Shot 2022-06-10 at 11 40 23 AM" src="https://user-images.githubusercontent.com/11710234/173101702-3e700d59-273c-4733-a9eb-4a852d7ebb54.png">

**Comment by danicahelb** [comment]
Hey @asizemore 
as we discussed in the 6/13 EDA UX meeting, if the user filters out data that effectively causes the numerator and denominator to be the same, please do not include an error message and allow the y-axis proportion to equal 1 (so there will be a straight line at y=1, which will give the user a clue that something is up).

Lets start here for b58, if we get feedback that it is confusing we can address this confusion later. thanks!

**Comment by asizemore** [comment]
Deployed to qa and feat. moving to ready for testing

**Comment by sweverschulman** [comment]
Functionality that when user makes the proportion = 1 to no throw an error but to plot y = 1 seems to be working. Functionality was also tested with PERCH study.
