### ISSUE TITLE
Computed bin width = 0 for number variables

### ISSUE THREAD

**Issue by jaycolin** [VEuPathDB/plot.data#185]
Many variables in recently reloaded datasets now have a computed bin width = 0 . Spot checked a production server (clinepidb.org  - eda058n) and the bin width there seems fine, so this must be a recent change in veupathUtils. During loading we run a script with:

`singularity exec docker://veupathdb/rserve
`
During execution a warning is printed but the process does not fail

```
1: In veupathUtils::nonZeroRound(binWidth, avgDigits) :
  Input is already zero and cannot be rounded to a non-zero number.
2: In veupathUtils::nonZeroRound(binWidth, avgDigits) :
  Input is already zero and cannot be rounded to a non-zero number.
3: In veupathUtils::nonZeroRound(binWidth, avgDigits) :
  Input is already zero and cannot be rounded to a non-zero number.

```

**Comment by asizemore** [comment]
Hmm. @jaycolin do you mind sharing one of the vars that has lots of unique values? 

Another way is we could do a more global check by inserting
```
if (uniqueN(v) < findNumBins(v)) {print("fewer unique values than bins!")}
```
on the line before the one that throws the warning (`data.binWidth = plot.data::findBinWidth(v);`) in your R script.

Then we can see if every time that warning is thrown, we also get the printout about fewer unique values than bins.

A var may have a huge range and many unique values, but depending on the spread of the data it's definitely possible to have the computed number of bins be larger than the number of unique values.

**Comment by jaycolin** [comment]
[head_circ.txt](https://github.com/VEuPathDB/plot.data/files/9161208/head_circ.txt)
This file has 195 distinct values. And there is only one pure 0.
I have run some tests and found that we get the correct result when the 0 is removed. When the 0 is included:

> In veupathUtils::nonZeroRound(binWidth, avgDigits) :
  Input is already zero and cannot be rounded to a non-zero number.

So I think plot.data just needs to handle that case by not trying to round it?

**Comment by asizemore** [comment]
Great - thanks @jaycolin ! 

At that point in the code, the `binWidth` already = 0, so even if plot.data didn't round it, we'd still end up with the binWidth=0 issue.

This new head_circ var is actually another case of having fewer unique values than number of calculated bins! There are 195 distinct values but the calculation that determines the number of bins gives 354! We have lots of distinct values but because of the distribution, we end up with many more bins.
The calculation for number of bins depends heavily on the interquartile range so having one 0 in the array is actually changing quite a lot. When i removed the 0 the calculated number of bins is only 21 so we don't see that error and binWidth is set to the correct non-zero value.

Jay - do you run plot.data from a particular tag or pull from master/main each time? I'll make a quick PR for the change that i think should solve this.

**Comment by bobular** [comment]
> So now my question is - is the check on unique values correct? Is it okay to have fewer unique values than bins? I'd think it'd be okay - @bobular what do you think? I'm not sure why we'd care about the number of unique values. Perhaps the number of actual values, but i dont follow why the number of unique vals matters.

I can't think why fewer unique values than bins should be a problem either! Could easily happen with subsetting.

**Comment by danicahelb** [comment]
related ticket: https://github.com/VEuPathDB/EdaNewIssues/issues/384

**Comment by SheenaTomko** [comment]
seems to be fixed now
