### ISSUE TITLE
Line plot response claims it's a scatter plot

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/plot.data#30]
This is because they are both implemented through the scatter class. I think the react component might be organized the same way. So if the UI guys are ok w it saying scatter then we can leave it. Otherwise I guess we'd have to subclass scatter.

**Comment by d-callan** [comment]
Subclassing means we can do things like explicitly remove the option for trend lines on a line plot, so maybe that's the better route anyhow

**Comment by moontrip** [comment]
Thank you for your information, @d-callan From my side, there is no problem to use either scatterplot or lineplot. Recently I changed lineplot viz to use the response with the name of "scatterplot" so that one can test lineplot via the feature site: I just tested that the lineplot works.

So just let me know if you would change it back to "lineplot", then I can change my code accordingly.

**Comment by d-callan** [comment]
if is no problem for @moontrip, i vote to leave it as is.
