### ISSUE TITLE
Backend: improve UMSP performance (profile and implement fixes)

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/plot.data#49]

**Comment by SheenaTomko** [comment]
Touched base with Danielle and main things to qa here and in #65 are 1) do things seem to still be working despite some fairly significant refactoring of the code and 2) does it take less time to see plots. the main offender was the scatter plot in umsp. there were a few requests there (mostly involving various combinations of age, date, weight and height) that were taking fairly significantly >1min. if we have most things under a minute, and age vs date around a minute, id say we were successful

UMSP is currently being reloaded, so will address on Tuesday

**Comment by SheenaTomko** [comment]
Didn't notice any issues with other studies when qc'ing other visualization-related tickets. 

Tested UMSP. Non-scatter plots (bar charts, histograms, etc.) took ~40 sec to load with and without overlay variables while a scatter plot of date vs age took 2 min. Date vs height with or without sex overlaid took 1.5 min. Not quite as fast as hoped for, but there's a separate [ticket ](https://github.com/VEuPathDB/web-eda/issues/291) to add a warning when the wait time will be long since there's lots of study data. This should be sufficient, so marking this as complete.
