### ISSUE TITLE
Gracefully handle listVar json - needed for custom taxa list picker

### ISSUE THREAD

**Issue by d-callan** [VEuPathDB/plot.data#54]
so using xaxes of box plots as an ex.. the column representing x tick labels in the resulting plot.data object will be called 'label' and there should be some xAxisVariableDetails that say things like entity space and variable id(s). i was just looking through tests for boxplot for a sort of related issue and im not sure thats whats currently being done.

**Comment by asizemore** [comment]
Currently, all listvars must have the same variable details, and then this is assigned to the new meltedVar. So in the boxplot example, the xAxisVariable has variableId="meltedVariable", entityId=NULL (because all are null currently), dataType="STRING", dataShape="CATEGORICAL".

**Comment by asizemore** [comment]
Would we need an extra attribute to hold all of the original listvar variableDetails? Or can we handle that elsewhere (java maybe?)?

**Comment by asizemore** [comment]
the listVar turns into two vars: a categorical var composed of original column names, and a continuous variable. We originally wanted a listvar so that we could select multiple taxa, which mean we know the name of the new continuous variable should be called "Relative abundance". If we let listVars exist more generally, then either the user will have to determine what the created continuous variable is called, or we'll need to determine that from the collection of vars in the listVar. All this to say that we'll need to figure this part out, but I don't think it needs to go through plot.data right now.

**Comment by d-callan** [comment]
@asizemore can we close this?

**Comment by asizemore** [comment]
Yes we can!!
